# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_history',
            name='jersey_number',
            field=models.IntegerField(default=None, max_length=300),
        ),
    ]
