# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0002_player_history_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='player_history',
            name='jersey_number',
            field=models.IntegerField(),
        ),
    ]
