# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0004_player_history_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Matchs_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(blank=True)),
                ('run', models.IntegerField(blank=True)),
                ('highest', models.IntegerField(blank=True)),
                ('scores', models.IntegerField(blank=True)),
                ('fifties', models.IntegerField(blank=True)),
                ('hundreds', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='logoUri',
            field=models.URLField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='player_history',
            name='jersey_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='player_matchs_history',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_series.Player_History'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='cricket_series.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='cricket_series.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='cricket_series.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='club_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cricket_series.State'),
        ),
    ]
