# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0005_auto_20200510_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_history',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='cricket_series.Team'),
        ),
    ]
