# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0006_auto_20200511_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_history',
            name='palyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
