# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0007_auto_20200512_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_history',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings.MEDIA_ROOT'),
        ),
    ]
