# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0008_player_history_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_history',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
