# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0009_auto_20200513_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logoUri',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
