# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_series', '0010_auto_20200513_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
